# Generated by Django 4.2.16 on 2024-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Укажите ТЭГ")),
            ],
        ),
        migrations.CreateModel(
            name="Old_Man",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        max_length=50, verbose_name="Укажите название тэга"
                    ),
                ),
                ("tags", models.ManyToManyField(to="hashtags.tag")),
            ],
        ),
    ]
