# Generated by Django 4.2.16 on 2024-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=50)),
                ('price', models.FloatField(default=100)),
                ('tags', models.ManyToManyField(to='hashtags.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Old_Man',
        ),
    ]
