# Generated by Django 4.2.16 on 2024-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtags", "0002_clothes_delete_old_man"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothes",
            name="thing",
        ),
        migrations.AddField(
            model_name="clothes",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
